services:
  - type: web
    name: mental-health-chatbot
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_CLOUD_API_KEY
        sync: false
      - key: CHROMA_CLOUD_TENANT
        sync: false
      - key: CHROMA_CLOUD_DATABASE
        sync: false
